# Generated by Django 4.2.30 on 2026-06-30 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand name, e.g. Toyota', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Short description of the brand')),
            ],
            options={
                'verbose_name': 'Car Make',
                'verbose_name_plural': 'Car Makes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Model name, e.g. Camry', max_length=100)),
                ('car_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Wagon', 'Wagon'), ('Hatchback', 'Hatchback'), ('Pickup', 'Pickup')], default='Sedan', help_text='Body type', max_length=10)),
                ('year', models.IntegerField(default=2023, help_text='Model year')),
                ('dealer_id', models.IntegerField(blank=True, help_text='ID of the dealer carrying this model (optional)', null=True)),
                ('car_make', models.ForeignKey(help_text='Manufacturer this model belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='models', to='djangoapp.carmake')),
            ],
            options={
                'verbose_name': 'Car Model',
                'verbose_name_plural': 'Car Models',
                'ordering': ['car_make', 'name', '-year'],
            },
        ),
    ]
